# Generated by Django 3.1.3 on 2020-11-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lente', models.BooleanField(verbose_name='Es un lente?')),
                ('distancia', models.CharField(choices=[('-', ''), ('lejos', 'Lejos'), ('cerca', 'Cerca')], default='-', max_length=20)),
                ('lado', models.CharField(choices=[('-', ''), ('izquierda', 'Izquierda'), ('derecha', 'Derecha')], default='-', max_length=20)),
                ('armazon', models.BooleanField(verbose_name='Incluye armazón?')),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
