# Generated by Django 3.1.3 on 2020-11-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20201130_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('Tarjeta de Credito', 'Tarjeta de Credito'), ('Billetera Virtual', 'Billetera Virtual'), ('Efectivo', 'Efectivo'), ('Debito', 'Debito')], default='Efectivo', max_length=20),
        ),
    ]
