# Generated by Django 3.1.3 on 2020-11-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20201120_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
    ]
