# Generated by Django 3.1.3 on 2020-11-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_auto_20201120_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='asistencia',
            field=models.CharField(choices=[('-', '-'), ('asistio', 'Asistió'), ('no_asistio', 'No Asistió')], default='-', max_length=20),
        ),
    ]
